baseURL: "http://www.anshulpatel.in"

title: "Anshul Patel"

languageCode: "en"
defaultContentLanguage: "en"


paginate: 10
enableEmoji: true

params:
  author: "Anshul Patel"
  description: "Anshul Patel's personal website"
  keywords: "geek, gamer, techie, blog, engineer"
  info:
    - Geek ğŸ¤“, Gamer ğŸ•¹ï¸, Techie ğŸ‘¨â€ğŸ’»
  avatarURL: "images/anshul.jpg"
  dateFormat: "January 02, 2006"
  colorScheme: "auto"
  customCSS:
    - "css/custom.css"
  footerQuote: "In my spare time, I plan World Domination from a secret villainous lair ğŸ¦¹â€â™‚ï¸."

languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        - name: "Meetups"
          weight: 1
          url: "/meetups/"

theme:
  - github.com/luizdepra/hugo-coder

module:
  mounts:
    - source: assets
      target: assets
