baseURL: "http://www.anshulpatel.in"

title: "Anshul Patel"

languageCode: "en"
defaultContentLanguage: "en"

paginate: 10
enableEmoji: true

googleAnalytics: "UA-93926186-1"

params:
  author: "Anshul Patel"
  description: "Anshul Patel's personal website"
  keywords: "geek, gamer, techie, blog, engineer"
  info:
    - Geek ğŸ¤“, Gamer ğŸ•¹ï¸, Techie ğŸ‘¨â€ğŸ’»
  avatarURL: "images/anshul.jpg"
  dateFormat: "January 02, 2006"
  colorScheme: "auto"
  customCSS:
    - "css/custom.css"
    - "css/fork-awesome.css"
  footerQuote: "In my spare time, I plan world domination from a secret villainous lair ğŸ¦¹â€â™‚ï¸."
  social:
    - name: "Github"
      icon: "fa fa-2x fa-github"
      weight: 1
      url: "https://github.com/anshulpatel25"
    - name: "Linkedin"
      icon: "fa fa-2x fa-linkedin"
      weight: 2
      url: "https://www.linkedin.com/in/anshul-patel-29a95635"
    - name: "Email"
      icon: "fa fa-2x fa-envelope"
      weight: 3
      url: "mailto:anshulpatel25@gmail.com"

languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        - name: "Posts"
          weight: 1
          url: "/posts/"
        - name: "Meetups"
          weight: 2
          url: "/meetups/"
        - name: "FOSS"
          weight: 3
          url: "/foss/"
        - name: "About"
          weight: 4
          url: "/about/"

theme:
  - github.com/luizdepra/hugo-coder

module:
  mounts:
    - source: assets
      target: assets
